### ISSUE TITLE
Update Base Period Transfer text when cancelled and in selection window

### ISSUE THREAD

**Issue by marlenebellman** [Angelikahagen/MainFRAM_VS-Repo#5]
Hello again - 

On approx line 684 in FVS_FramUtils.vb under the subroutine TransferBPBtn_Click, there is a message box that prompts when a base period transfer is cancelled.  Currently the MsgBox states "Model Run Transfer Cancelled" and I would propose to update that text to read "Base Period Transfer Cancelled".

On approx line 156 in FVS_ModelRunSelection.vb under the subroutine FVS_ModelRunSelection_Load, there is a ElseIF statement for RecordsetSelectionType = 3 or 11 then contains the RSTitle.Text = "Model Run TRANSFER Selections".  I propose that this be edited for when RecordsetSelectionType = 11 the RSTitle.Text = "Base Period TRANSFER Selections".  The previous text is only specific to model run transfer buttons/protocols and the objective is to clearly present when base period transfer protocols are being used instead.

Thanks!  Marlene

**Comment by Angelikahagen** [comment]
done
